version: '3.7'

services:
  vue:
    container_name: vue
    build:
      context: .
      dockerfile: DockerFile.vue
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8081:8001"
    stdin_open: true
    tty: true
    networks:
      - dev
networks:
  dev:
    external:
      name: dev